### PR TITLE
Change build system to dune

### LINKED ISSUE #19: Switch to jbuilder/dune
Since it is becoming a de-facto standard.

### PR DESCRIPTION
**Pull request by psafont**
Changing the build system to use dune allows out-of-the-box compatibility with ctypes-foreign 0.18 and greater.

This change also generates 3 new libraries public, unfortunately. They are not useful to the users and are a byproduct on not being able to have private libraries inside public ones they are unix_errno.bindings, unix_errno.types and unix_errno.types.detected.

I need to investigate whether the change is making dlm to fail to link when using ctypes 0.18.0 while it works when using lower versions of ctypes.

Comments, suggestions and pointers from anybody reading the PR are very much welcome, the porting process was quite complicated to me and might have missed several issues.

fixes #19
obsoletes #20

### CODE REVIEW

**Comment by psafont** [comment]
2 binaries are missing

**Comment by psafont** [comment]
Updated to dune 2.8 to keep most libraries private:

```
$ opam show unix-errno --list-files
/home/paus/.local/share/opam/toolstack-local/bin/errno-map
/home/paus/.local/share/opam/toolstack-local/doc/unix-errno
/home/paus/.local/share/opam/toolstack-local/doc/unix-errno/CHANGES
/home/paus/.local/share/opam/toolstack-local/doc/unix-errno/README.md
/home/paus/.local/share/opam/toolstack-local/lib/stublibs/dllunix_errno_stubs.so
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/META
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/.public_cmi/unix_errno_bindings.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/.public_cmi/unix_errno_bindings.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/errno_bindings.a
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/errno_bindings.cma
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/errno_bindings.cmxa
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/errno_bindings.cmxs
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/unix_errno_bindings.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_bindings/unix_errno_bindings.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/.public_cmi/unix_errno_generated.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/.public_cmi/unix_errno_generated.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/.public_cmi/unix_errno_types.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/.public_cmi/unix_errno_types.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/errno_types.a
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/errno_types.cma
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/errno_types.cmxa
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/errno_types.cmxs
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/unix_errno_generated.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/unix_errno_generated.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/unix_errno_types.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types/unix_errno_types.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/.public_cmi/unix_errno_types_detected.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/.public_cmi/unix_errno_types_detected.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/errno_types_detected.a
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/errno_types_detected.cma
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/errno_types_detected.cmxa
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/errno_types_detected.cmxs
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/unix_errno_types_detected.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/__private__/errno_types_detected/unix_errno_types_detected.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/dune-package
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.a
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.cma
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.cmti
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.cmxa
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.cmxs
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/errno.mli
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.a
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.cma
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.cmti
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.cmxa
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.cmxs
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_host.mli
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_linux_4_4_6.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_linux_4_4_6.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_linux_4_4_6.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_linux_4_4_6.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_osx_10_11_4.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_osx_10_11_4.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_osx_10_11_4.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/host/errno_map_osx_10_11_4.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/opam
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/errno_unix.cmi
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/errno_unix.cmt
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/errno_unix.cmti
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/errno_unix.cmx
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/errno_unix.ml
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/errno_unix.mli
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/libunix_errno_stubs.a
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/unix_errno.a
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/unix_errno.cma
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/unix_errno.cmxa
/home/paus/.local/share/opam/toolstack-local/lib/unix-errno/unix/unix_errno.cmxs
```

compared to the previous version:

```
$ opam show unix-errno --list-files
/home/paus/.local/share/opam/toolstack/bin/errno-map
/home/paus/.local/share/opam/toolstack/bin/errno-srcgen
/home/paus/.local/share/opam/toolstack/lib/stublibs/dllunix_errno_stubs.so
/home/paus/.local/share/opam/toolstack/lib/stublibs/dllunix_errno_stubs.so.owner
/home/paus/.local/share/opam/toolstack/lib/unix-errno
/home/paus/.local/share/opam/toolstack/lib/unix-errno/META
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno.cmi
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno.cmti
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno.cmx
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno.mli
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_.a
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_.cma
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_.cmxa
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_host.cmi
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_host.cmti
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_host.cmx
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_host.mli
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_unix.cmi
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_unix.cmti
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_unix.cmx
/home/paus/.local/share/opam/toolstack/lib/unix-errno/errno_unix.mli
/home/paus/.local/share/opam/toolstack/lib/unix-errno/libunix_errno_stubs.a
/home/paus/.local/share/opam/toolstack/lib/unix-errno/unix_errno.a
/home/paus/.local/share/opam/toolstack/lib/unix-errno/unix_errno.cma
/home/paus/.local/share/opam/toolstack/lib/unix-errno/unix_errno.cmxa
```

The DLM bindings still fail to link when using ctypes 0.18 on my system, but it works on 0.17.1:
```
/usr/bin/ld: lib_gen/dlm_bindings.a(dlm_bindings__Bindings.o): in function `camlDlm_bindings__Bindings__1':
:(.data+0x128): undefined reference to `unix_error_of_code'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
    ocamlopt lib_gen/stubgen_ml.exe (exit 2)
```

**Comment by dsheets** [comment]
I no longer maintain this library. Please feel free to fork it and publish your fork under the same name. I am going to mark this repo as archived. If you decide to fork and publish, let me know and I will redirect from here to your fork. Thanks!

**Comment by psafont** [comment]
I've create a PR against the fork, thanks for your work on the library!

https://github.com/xapi-project/ocaml-unix-errno/pull/1

**Comment by lindig** [comment]
We have cloned this: https://github.com/xapi-project/ocaml-unix-errno

**Comment by psafont** [comment]
@dsheets We've released 2 versions, feel free to archive this repository: https://opam.ocaml.org/packages/unix-errno/
